name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v1

    - name: Executing remote command
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: |
          ls
          cd /root/speedycertz
          ls
        

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        node-version: ${{ matrix.node-version }}
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: lsof -wni tcp:3000
    - run: npm install
    - run: npm run build --if-present
    - run: pm2 reload next-js
      env:
        CI: true
