name: Deploy Next.js App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
    - uses: actions/checkout@v2

    - name: Fetch codebase
      uses: appleboy/scp-action@master
      env:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/root/speedy-certz"
    
    - name: Deploy Code
      uses: appleboy/ssh-action@master
      with:
        node-version: ${{ matrix.node-version }}
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: |
          pwd
          ls -ltr
          cd /root/speedy-certz
          ls -ltr
          npm install
          npm run build --if-present
          npm install pm2 -g
          pm2 start npm --name "speedy-certz" -- start --port 3000
      env:
        CI: true
