name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
    - uses: actions/checkout@v2

    - name: Fetching code and deploying on 
      uses: appleboy/ssh-action@master
      with:
        node-version: ${{ matrix.node-version }}
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: |
    - run: pwd
    - run: ls -ltr
    - run: cd /root/speedy-certz
    - run: ls -ltr
    - run: npm install
    - run: npm run build --if-present
    - run: npm install pm2 -g
    - run: pm2 start npm --name "speedy-certz" -- start --port 3000
      env:
        CI: true
